services:
  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/ninacare-laravel-vue:latest
    container_name: laravel_app
    restart: always
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - prod

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt
    networks:
      - prod

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - prod

volumes:
  db_data:

networks:
  prod: