services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel_db}
      MYSQL_USER: ${MYSQL_USER:-laravel}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
