name: Deploy to Production

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --pull --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/ninacare-laravel-vue:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ninacare-laravel-vue:latest

      - name: SSH and deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e  # Stop immediately if a command fails
            cd /var/www/ninacare-laravel-vue
            docker-compose -f docker-compose.prod.yaml pull
            docker-compose -f docker-compose.prod.yaml up -d --remove-orphans
            docker image prune -af --filter "until=24h"
